environment:
  symbol: ETH
  data_path: data/features/encoder_windows_eth_small_emb.parquet
  market_config: config/markets.yaml
  cost_config: config/costs.yaml
  execution_profile: backtesting
  order_types:
    - market
    - limit
  limit_order_fill_bps: 5.0
  limit_offset_bps:
    - 5.0
    - 10.0
  bracket_take_profit_bps:
    - 15.0
  bracket_stop_loss_bps:
    - 10.0
  position_sizes:
    - -1.0
    - -0.5
    - 0.0
    - 0.5
    - 1.0
  episode_length: 256  # Match training config
  trading_cost_bps: 1.0
  max_position: 1.0
  include_position_in_obs: true  # Enable position state in observations
  reward:
    trading_cost_bps: 1.0
    holding_cost_bps: 0.2
    risk_aversion: 0.001
    reward_clip:
      - -0.05
      - 0.05
    normalize_pnl: true  # Enable log(1 + pnl/equity) normalization
    initial_equity: 10000.0
evaluation:
  episodes: 5
  random_policy: false
  model_path: models/policies/ppo_trading_env.zip
