architecture:
  model_type: tcn
  input:
    window_length: 256
    num_timeframes: 4
    feature_dim: 20
  tcn:
    num_channels:
    - 64
    - 128
    - 256
    - 256
    kernel_size: 3
    dropout: 0.2
    dilation_base: 2
    embedding_dim: 256
  transformer:
    d_model: 256
    nhead: 8
    num_layers: 6
    dim_feedforward: 1024
    dropout: 0.1
    activation: gelu
    positional_encoding: relative
    max_seq_len: 2048
  lstm:
    hidden_size: 256
    num_layers: 2
    dropout: 0.2
    bidirectional: false
    embedding_dim: 256
heads:
  masked_reconstruction:
    enabled: true
    mask_ratio: 0.15
    loss_weight: 1.0
    output_dim: 4
  regime_classifier:
    enabled: true
    num_classes: 4
    loss_weight: 0.5
    hidden_dim: 128
    dropout: 0.3
  sr_heatmap:
    enabled: false
    grid_size: 64
    price_range_pct: 0.05
    loss_weight: 0.8
    hidden_dim: 128
    output_activation: sigmoid
  quantile_forecasting:
    enabled: false
    num_quantiles: 9
    horizons:
    - 1
    - 3
    - 5
    - 15
    loss_weight: 1.0
    hidden_dim: 128
  pattern_classifier:
    enabled: false
    num_classes: 3
    loss_weight: 0.3
    hidden_dim: 128
    dropout: 0.3
training:
  optimizer: adamw
  learning_rate: 0.0003
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.999
  lr_scheduler:
    type: cosine_annealing
    warmup_epochs: 0
    min_lr: 1.0e-05
    T_max: 5
  batch_size: 64
  num_epochs: 5
  gradient_clip_norm: 1.0
  accumulation_steps: 1
  val_split: 0.2
  early_stopping:
    enabled: true
    patience: 3
    metric: val_total_loss
    mode: min
  augmentation:
    noise_std: 0.001
    time_warp: true
    magnitude_warp: true
  label_smoothing: 0.1
  mixup_alpha: 0.0
compute:
  device: cpu
  mixed_precision: false
  num_workers: 0
  pin_memory: false
  compile: false
checkpointing:
  save_dir: models/encoders
  save_every_n_epochs: 10
  keep_last_n: 3
  save_best: true
  best_metric: val_total_loss
logging:
  use_mlflow: false
  experiment_name: agv2_encoder_pretraining
  log_every_n_steps: 50
  log_gradients: false
  log_embeddings: true
