# AGV2 Training Pipeline Configuration

# Symbol to train
symbol: ETH

# Input/Output paths
raw_data_path: data/raw/eth_1m.parquet
output_dir: experiments/eth_latest

# Config files for each stage
encoder_config: config/encoder.yaml
policy_config: config/rl_policy.yaml
backtest_config: config/backtest.yaml

# Pipeline control (set to true to skip steps)
skip_features: false      # Skip feature engineering
skip_encoder: false       # Skip encoder training (Stage 1)
skip_embeddings: false    # Skip embedding generation
skip_policy: false        # Skip policy training (Stage 2)
skip_backtest: false      # Skip final backtesting

# Compute
device: auto  # auto, cuda, or cpu

# Feature engineering settings
features:
  include_volatility: true
  vol_windows: [10, 30, 60]
  horizons: [1, 3, 12, 60]

# Evaluation
backtest_episodes: 50  # Number of episodes for final backtest
